### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by strika** [mimimalizam/nasa#3]
This link is broken:

<img width="556" alt="screen shot 2017-12-28 at 10 48 02 am" src="https://user-images.githubusercontent.com/737903/34407071-bf540a14-ebbc-11e7-8a9f-d2dc29e3ad19.png">

Thanks for making this public!

**Comment by aaronmaynard** [comment]
📝 Created Pull request with correct markdown

**Comment by mimimalizam** [comment]
@strika tnx for the words of encouragement and for opening the issue 
tnx to @aaronmaynard url is fixed, so closing the issue. 

👏  🙇
